name: Dela does it
favicon: null
layout_spectrum: 0.49447
typography_spectrum: 0.50263
title: FoodFish
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2c2c2'
    - '#a78770'
    - '#241b14'
    - '#ffffff'
    - '#9d2100'
  brandStrength: 0.42873887973837554
  lightness: 0.37562003917992115
  saturation: 0.6475011000875384
  rhythmicContrast: 0.7160841468721628
purpose: []
